name: Convert All Markdown to MP3

on:
  push:
    branches:
      - production  # Specify your branch here if needed
    paths:
      - 'content/**/*.md'
  pull_request:
    paths:
      - 'content/**/*.md'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          JSON_ARRAY=$(find content -name '*.md' | jq -R -s -c '[inputs | {filePath: .}]')
          echo "::set-output name=matrix::$JSON_ARRAY"

  convert:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    uses: wgu-programs/workflows/.github/workflows/convert-md-to-mp3.yml@main
    with:
      filePath: ${{ matrix.filePath }}
      apiKey: ${{ secrets.API_KEY }}
      voice: 'en-US-Wavenet-F'
