name: Convert All Markdown to MP3

on:
  push:
    branches:
      - main  # Specify your branch here if needed
    paths:
      - 'content/**/*.md'
  pull_request:
    paths:
      - 'content/**/*.md'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          echo "matrix::$(find content -name '*.md' | jq -R -s -c '[split("\n")[] | select(. != "") | {filePath: .}]')" >> $GITHUB_ENV

  convert:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: Convert Markdown to MP3
        run: curl -X POST "https://example.com/api/convert" --data "filePath=${{ matrix.filePath }}" --header "apiKey: ${{ secrets.API_KEY }}" --header "voice: en-US-Wavenet-F"
