name: "Process Changed Markdown Files"

on:
  push:
    paths:
      - 'content/**/*.md'
  pull_request:
    paths:
      - 'content/**/*.md'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.md$' | jq -R -s -c 'split("\n")[:-1] | map({filePath: .})')"
        shell: bash

  convert:
    needs: prepare
    uses: wgu-programs/workflows/.github/workflows/convert-md-to-mp3.yml@main
    with:
      apiKey: ${{ secrets.ELEVENLABS_API_KEY }}
      voice: 'en-US-Wavenet-F'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    matrix: ${{fromJson(needs.prepare.outputs.matrix)}}