name: Generate Audio from Markdown

on:
  workflow_call:
    inputs:
      files:
        description: 'List of changed markdown files'
        required: true
        type: string

jobs:
  generate-audio:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run Generate Audio Script
      run: node tts/generate-audio.js ${{ inputs.files }}
