name: "Generate Audio"

on:
  push:
    paths:
      - 'content/**/*.md'
  pull_request:
    paths:
      - 'content/**/*.md'

jobs:
  process-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This fetches all history for all branches and tags

      - name: Find Markdown files changed
        id: files
        run: |
          echo "FILES_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'content/.*\.md$')" >> $GITHUB_ENV
        shell: bash

      - name: Process each Markdown file
        if: ${{ env.FILES_CHANGED != '' }}
        run: |
          for file in $FILES_CHANGED; do
            if [ -f "$file" ]; then
              echo "Processing $file"
              
              - name: Convert Markdown to MP3
                uses: wgu-programs/workflows/.github/workflows/convert-md-to-mp3.yml@main
                with:
                  filePath: $file
                  apiKey: ${{ secrets.ELEVENLABS_API_KEY }}
                  voice: 'en-US-Wavenet-F'
            fi
          done
        shell: bash