name: Convert All Markdown to MP3

on:
  push:
    paths:
      - 'content/**/*.md'
  pull_request:
    paths:
      - 'content/**/*.md'

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Find Markdown Files
        id: find-md
        run: |
          echo "markdown_files=$(find content -name '*.md')" >> $GITHUB_ENV
      
      - name: Convert Markdown Files to MP3
        uses: wgu-programs/workflows/.github/workflows/convert-md-to-mp3.yml@main
        with:
          filePath: ${{ env.markdown_files }}
          apiKey: ${{ secrets.API_KEY }}
          voice: 'en-US-Wavenet-F'