name: "Process Changed Markdown Files"

on:
  push:
    branches:
      - main  # Ensure this is the branch you want to monitor
    paths:
      - 'content/**/*.md'
  pull_request:
    paths:
      - 'content/**/*.md'

jobs:
  find-markdown-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.filter-files.outputs.markdown-files }}
    steps:
      - uses: actions/checkout@v3
      - id: filter-files
        run: |
          echo "::set-output name=markdown-files::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.md$' | jq -R -s -c 'split("\n")[:-1]')"

  convert-markdown:
    needs: find-markdown-files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.find-markdown-files.outputs.files) }}
    steps:
      - uses: actions/checkout@v3
      - uses: wgu-programs/workflows/.github/workflows/convert-md-to-mp3.yml@main
        with:
          apiKey: ${{ secrets.ELEVENLABS_API_KEY }}
          voice: 'en-US-Wavenet-F'
          filePath: ${{ matrix.file }}